import Head from 'next/head';

export default function Home() {
  return (
    <div
      sx={{
        display: 'flex',
        flexDirection: 'column',
        // set this to `minHeight: '100vh'` for full viewport height
        minHeight: `100vh`,
      }}
    >
      <Head>
        <title>import export</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        sx={{
          width: '100%',
        }}
      >
        Header
      </header>
      <main
        sx={{
          width: '100%',
          flex: '1 1 auto',
        }}
      >
        Main
      </main>
      <footer
        sx={{
          width: '100%',
        }}
      >
        Footer
      </footer>
    </div>
  );
}
